# Generated by Django 3.2.8 on 2021-10-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
