# Generated by Django 3.2.8 on 2021-11-06 14:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekshop', '0004_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='URL'),
        ),
    ]
