# Generated by Django 3.2.8 on 2021-11-06 14:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekshop', '0005_auto_20211106_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',), verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',), verbose_name='URL'),
        ),
    ]
