# Generated by Django 3.2.8 on 2021-11-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekshop', '0008_auto_20211106_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='products',
            field=models.ManyToManyField(related_name='category', to='geekshop.Product', verbose_name='Товары в категории'),
        ),
    ]
