# Generated by Django 3.2.8 on 2021-10-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
