# Generated by Django 3.2.8 on 2021-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия ключа активации'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='register_activation_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ключ активации'),
        ),
    ]
