# Generated by Django 3.2.8 on 2021-11-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekshop', '0004_alter_productcategory_slug'),
        ('basket', '0002_auto_20211101_0614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketProduct',
            new_name='BasketItem',
        ),
    ]
